### ISSUE TITLE
Show a marker/pin on the map

### ISSUE THREAD

**Issue by Bertware** [oSoc18/OASIS#28]
Show a test marker on the Open Street Map to research how to interact with the map

**Comment by Bertware** [comment]
See also: https://github.com/PaulLeCam/react-leaflet/blob/master/example/components/simple.js

**Comment by Bertware** [comment]
We need to specify the icon as an object:
https://leafletjs.com/reference-1.3.0.html#icon

**Comment by HennecartLisa** [comment]
see also #36

**Comment by Bertware** [comment]
See commits https://github.com/oSoc18/OASIS/commit/c172d9bd2e6110ef110cc0413ccf9dc234082c62 https://github.com/oSoc18/OASIS/commit/06470ef36de62a565e2d650895f1659ab1ac0bb2
